# Generated by Django 5.0.3 on 2024-04-03 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.TextField()),
                ('Subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Monday', models.TextField()),
                ('Tuesday', models.TextField()),
                ('Wednesday', models.TextField()),
                ('Thursday', models.TextField()),
                ('Friday', models.TextField()),
                ('Saturday', models.TextField()),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.TextField()),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Hometasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.TextField()),
                ('Description', models.TextField()),
                ('Date', models.DateTimeField()),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.classes')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.TextField()),
                ('Date', models.DateTimeField()),
                ('StydentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.students')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.teachers')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='TeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.teachers'),
        ),
    ]
